<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>系统发生错误</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8"/>
<meta name="Generator" content="EditPlus"/>
<style>
body{
	font-family: 'Microsoft Yahei', Verdana, arial, sans-serif;
	font-size:14px;
}
a{text-decoration:none;color:#174B73;}
a:hover{ text-decoration:none;color:#FF6600;}
h2{
	border-bottom:1px solid #DDD;
	padding:8px 0;
    font-size:25px;
}
.title{
	margin:4px 0;
	color:#F60;
	font-weight:bold;
}
.message,#trace{
	padding:1em;
	border:solid 1px #000;
	margin:10px 0;
	background:#FFD;
	line-height:150%;
}
.message{
	background:#FFD;
	color:#2E2E2E;
		border:1px solid #E0E0E0;
}
#trace{
	background:#E7F7FF;
	border:1px solid #E0E0E0;
	color:#535353;
}
.notice{
    padding:10px;
	margin:5px;
	color:#666;
	background:#FCFCFC;
	border:1px solid #E0E0E0;
}
.red{
	color:red;
	font-weight:bold;
}
.green{
	color:green;
}
.style1 {
	color: #174B73;
}
</style>
</head>
<body>
<div class="notice">
<h2>There is an Exception </h2>
<div >you can [ <a href="javascript:void(0);" onclick="javascript:location.reload();">try</span></a> ] [ <a href="javascript:history.back()">
	back</span></a> ]</div>
<?php
if ($trace = $e->getTrace()) {
	$msg = $e->getMessage();
	$file = $e->getFile();
	$line = $e->getLine();
?>
<p><strong>Exception Location:</strong>　FILE: <span class="red"><?php echo $file ;?></span>　LINE: <span class="red"><?php echo $line;?></span></p>
<p class="title">[ Exception Message ]</p>
<p class="message"><?php echo $msg;?></p>
<p class="title">[ TRACE ]</p>
<?php
	$trace = $trace[0]['args'] ? array_slice($trace, 1) : $trace;
	foreach ($trace as $traceinfo) {
?>
<p id="trace">
<span class="green">File :</span>
<?php echo nl2br($traceinfo['file']);?>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span class="green">Function :</span>
<?php echo (isset($traceinfo['class'])?$traceinfo['class'].$traceinfo['type']:null).$traceinfo['function'];?>
</p>
<?php
	}
}
?>
</div>
<div align="center" style="color:#FF3300;margin:5pt;font-family:Verdana">
	<span style='color:silver'> Powered by Yijian.cen</span>
</div>
</body>
</html>